### ISSUE TITLE
cronR Rstudio addin fails

### ISSUE THREAD

**Issue by GeraldCNelson** [bnosac/cronR#17]
I have added the necessary packages and the Cron job scheduler window opens fine. I choose a script, launch date and launch hour. I also add a Job description. When I click Create job, I get the following messages in the Console 

Listening on http://127.0.0.1:3294
Adding cronjob:
---------------

```
## cronR job
## id:   job_d1251755985c1afd78e975fd279c6b7b
## tags: 
## desc: Run PAmonitorscreenshot script
16 * * * * /Library/Frameworks/R.framework/Resources/bin/Rscript '/Users/gcn/Documents/workspace/PAmonitors/PAscreenshots.R'  >> '/Users/gcn/Documents/workspace/PAmonitors/PAscreenshots.log' 2>&1
crontab: tmp/tmp.2463: Operation not permitted
```

Suggestions on how to fix appreciated!

**Comment by jwijffels** [comment]
Looks like you don't have rights on crontab.
Are you running Mac OS. Probably the solution is shown here: https://serverfault.com/questions/954586/osx-mojave-crontab-tmp-tmp-x-operation-not-permitted

**Comment by GeraldCNelson** [comment]
I am on a Mac. And I had already implemented the fix proposed in that link. But could the Rstudio addin may be looking at a different cron?

**Comment by jwijffels** [comment]
cronR use calls crontab sometempfile where sometempfile contains all cronjobs. See https://github.com/bnosac/cronR/blob/cbaab8a73cb1c4df3e6fabbccc377b393503d1e1/R/cron_add.R#L232. If your user does not have the rights to do this, this will fail

**Comment by jwijffels** [comment]
Maybe look for the term cron on this page http://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/
or call steve jobs :)

**Comment by wmcraver** [comment]
@GeraldCNelson I had the same issue.  I used @jwijffels URL and found the piece below.  This solved the issue for me.  Adding Terminal or R or RStudio to the Full Disk Access doesn't do anything because it's actually crontab that needs the access to write the cron job.

---------
Instead, you should add "crontab" to “System Preferences > Security & Privacy > Full Disk Access”.

I did this by running "open /usr/bin/", which opened a Finder window that allowed me to easily drag/drop the "crontab" program into the “Full Disk Access” list.

**Comment by jwijffels** [comment]
Closing as solution was indicated by @wmcraver . Thanks!

**Comment by scworland** [comment]
in addition to crontab, I also had to give R and Rstudio full disk access for the plugin to work

![image](https://user-images.githubusercontent.com/11577981/65061284-99568380-d947-11e9-8495-8927b90e7510.png)

**Comment by nicocriscuolo** [comment]
Thanks @wmcraver!!!
