### ISSUE TITLE
Using cronR with EIKON API (thomson reuters)

### ISSUE THREAD

**Issue by Nygdat** [bnosac/cronR#2]
Hi,
I would like to use this package to schedule my script. However when I run my script through the scedule app I get an error. When I just run in the RStudio it works. 

The problem seems to be the function "set_app_id" in this package https://github.com/ahmedmohamedali/eikonapir

Here is my code and log.output:

library(eikonapir)
set_app_id('F3AEA95748854609FA504275')

Log output
Error in new("RequestInfo", application_id = appId, port = 36036L, url = request_url,  : 
  could not find function "new"
Calls: set_app_id -> RequestInfo
Execution halted

Do you have any idea why this is working in RStudio, but not when I run it using cronR?

**Comment by jwijffels** [comment]
I presume it's as follows.

The function 'new' where you get the error message from (could not find function "new") is from the methods package. This package is not loaded automatically when launched through Rscript which is what cronR does, but is in RStudio.

The fix is to add library(methods) to your script

**Comment by Nygdat** [comment]
Yes,  thank you very much!
