### ISSUE TITLE
package was removed on CRAN

### ISSUE THREAD

**Issue by jwijffels** [bnosac/cronR#46]
```
Package ‘cronR’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2021-09-02 for policy violation.

A summary of the most recent check results can be obtained from the check results archive.

Please use the canonical form https://CRAN.R-project.org/package=cronR to link to this page.
```

The package should not do cron_rm / cron_add / cron_clear / cron_load without manual confirmation by the user, nor in examples nor in unit tests, nor in the webapp.

**Comment by jwijffels** [comment]
Hello @heds1 
The package was removed from CRAN after uploading the newest version mainly including your changes. I've changed the defaults such that approval by the user is always done before changing the cron schedule.
I need some 3rd eyes to check. Can you see if all works fine for your settings & scripts.

**Comment by heds1** [comment]
Hi -- it wasn't removed because of my changes, was it? I didn't add any tests that call any cron jobs. I've pulled down this version and tested it on my system, everything seems to be working as expected, and all 26 tinytest tests pass ok.

I do wonder about testing `cron_clear`. I'm not sure how hard it would be, but one option could be to save all the user's cron jobs before running `cron_clear`; verifying that they have all been removed; and then re-adding all those jobs. Even with the warning, I'm not sure if it's a good idea to be testing that as-is (it's pretty easy to just type "y" without properly reading the prompt when you run tinytest, and delete all your existing jobs).

Happy to help with a PR if you'd like anything specific.

**Comment by jwijffels** [comment]
It was removed because the package wiped out some of the internal CRAN cron processes running on their machines :(
I think the culprit was the vignette where eval=FALSE was not set, whiping out everything with cron_clear. If someone executes the vignette, the cron jobs of the user are gone. That's probably what happened on CRAN, and was triggered by the R CMD check error on M1 Mac. Probably there the cron jobs got whiped off :( and the owner of the machine did probably not understand where this was coming from as his cron jobs were now empty, it could as well have been an hacker. Completely understand that they removed the package from CRAN for that reason.
The tests are now to be executed in interactive mode only, so you need to execute `tinytest::test_package("cronR")`.
I'm not sure what you mean with the extra option in cron_clear, feel free to make a pull request
